### PR TITLE
updated version of pdfjs-dist package

### PR DESCRIPTION
**Pull request by islambek01**

### CODE REVIEW

**Comment by andyhot** [comment]
Does this resolve https://github.com/smith-carson/ember-pdf-js/issues/24 ?

**Comment by andyhot** [comment]
This would also resolve https://github.com/smith-carson/ember-pdf-js/issues/21 - and i think it warrants a version bump to 1.0.0

@marceloandrader Are you guys still using this? Do you want to give this a try with the latest `pdfjs-dist` version?

**Comment by marceloandrader** [comment]
hey @andyhot yes we still use it, I dont' have time today but I can check next week. We use some APIs for searching so I hope they are compatible.

**Comment by andyhot** [comment]
thx @marceloandrader - well, if we bump this to 1.0.0 you can still use the version you use and later on upgrade at will. @islambek01 won't that also work for you?

**Comment by islambek01** [comment]
> Does this resolve #24 ?

Yes. @andyhot

**Comment by islambek01** [comment]
> thx @marceloandrader - well, if we bump this to 1.0.0 you can still use the version you use and later on upgrade at will. @islambek01 won't that also work for you?

@andyhot Thank's a lot for making this package which solves our real problem))
so, when the latest 1.0.0 version of ember-pdf-js will be ready in npmjs.com?
 We are using ember-pdf-js, there is an error  #24 in our production. I have to solve it as soon as possible for our production app.

**Comment by marceloandrader** [comment]
hey @islambek01 just checked out your branch and tried to run the tests and the code is not compatible with PDFJs 2.3 you will have to make the modifications to make the tests pass. For example that version doesn't have a PDFJS global, now is pdfjsViewer and other couple globals, I tried changing that but looks like the API also changed. To merge this at least the tests must pass.

**Comment by islambek01** [comment]
> hey @islambek01 just checked out your branch and tried to run the tests and the code is not compatible with PDFJs 2.3 you will have to make the modifications to make the tests pass. For example that version doesn't have a PDFJS global, now is pdfjsViewer and other couple globals, I tried changing that but looks like the API also changed. To merge this at least the tests must pass.

@andyhot, I updated pdfjs-dist package to version 1.9.486 and it's compatible all tests passed. And issue #24 was solved by pdfjs-dist above the version - 1.8.170.

**Pull request merged**
